pub mod bm25;
pub mod client;
pub mod embedder;
pub mod kb;
pub mod native;
pub mod ollama;
pub mod openai;
pub mod gemini;
pub mod anthropic;
pub mod pipeline;
pub mod prompt;
pub mod reranker;
pub mod retriever;
pub mod utils;

pub use client::{AiClient, CommandResponse, OutputSummary};
pub use native::NativeModelClient;
pub use ollama::OllamaClient;
pub use openai::OpenAiClient;
pub use gemini::GeminiClient;
pub use anthropic::AnthropicClient;
pub use pipeline::RagPipeline;
pub use prompt::{system_prompt, output_summary_prompt, followup_prompt};
